- name: task level variables
  hosts: local
  connection: local
  vars: #play level variables
    course: "DevOps"
    Duration: 50 hours
  tasks:
  - name: text from task1
    vars: #task level variables
      course: "ansible"
      duration: 10 hours
    ansible.builtin.debug:
      msg: "course is {{course}} and duration is {{duration}}"
  - name: text from task2
    ansible.builtin.debug:
      msg: "course is {{course}} and duration is {{Duration}}"