- name: task level variables
  hosts: local
  connection: local
  vars:
    course: "DevOps"
    Duration: 50 hours
  tasks:
  - name: text from task1
    vars:
      course: "ansible"
      duration: 10 hours
    ansible.builtin.debug:
      msg: "course is {{course}} and duration is {{Duration}}"
  - name: text from task2
    ansible.builtin.debug:
      msg: "course is {{course}} and duration is {{Duration}}"