- name: variables from file
  hosts: local
  connection: local
  vars_prompt:
    - name: course
      prompt: "Enter course name"
      private: no
    - name: Duration
      prompt: "Enter course duration"
  tasks:
  - name: text from task1
    ansible.builtin.debug:
      msg: "course is {{course}} and duration is {{Duration}}"