- name: task level variables
  hosts: local
  connection: local
  vars: #play level variables
    Greet: "Hello from server admin"
  vars_files:
    - vars-file.yaml
  vars_prompt:
    - name: print
      prompt: "Enter the message"
      private: false
  tasks:
   - name: Print the message
      vars: #task level variables
      Greet: "Hello from server admin"
      ansible.builtin.debug:
        msg: "{{Greet}}"