- name: datatypes
  hosts: local
  connection: local
  vars: 
      course: "Devops with AWS" #string
      Duration: 120 hours #number
      topics: #list
        - Linux
        - AWS
        - Ansible
        - Docker
        - Kubernetes
      live:yes
      recorded: no
      tools: #dictionary
        ci: Jenkins
        container: Docker
        orchestration: Kubernetes
        cloud: AWS
  tasks:
    - name: text from task
      ansible.builtin.debug:
        msg: "course is {{course}} and duration is {{Duration}} and topics are {{topics}} is it live {{live}} is recorderd available {{recorded}} and tools are {{tools}}"
