- name: install packages
  hosts: web
  become: yes
  tasks:
  - name: Install packages
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{item.state}}"
    loop:
    - {name: 'mysql', state: 'present'}
    - {name: 'httpd', state: 'absent'}
    - {name: 'zip', state: 'present'}
    - {name: 'phython3', state: 'present'}