- name: install packages
  hosts: web
  become: yes
  tasks:
  - name: Install packages
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{item.state}}"
    loop:
    - {name: gcc, state: absent}
    - {name: msql, state: Present}
    - {name: httpd, state: Present}
    - {name: zip, state: absent}
    - {name: git,state: Present}