- name: filters
  hosts: local
  connection: local
  tasks:
  - name: handle undefined variables
    ansible.builtin.debug:
      msg: "hello {{person | default('world')}}"

  - name: convert string to list
    vars:
      courses: "devops,aws,azure,gcp"
    ansible.builtin.debug:
      msg: "courses are {{ courses | split(',') }}"

