- name: filters
  hosts: local
  connection: local
  tasks:
  - name: handle undefined variables
    ansible.builtin.debug:
      msg: "hello {{person | default('world')}}"

  - name: convert string to list
    vars:
      courses: "devops,aws,azure,gcp"
    ansible.builtin.debug:
      msg: "courses are {{ courses | split(',') }}"

  - name: convert map to list
    vars:
      courses: 
        name: "devops"
        duration: "2 months"
        platform: "joindevops"
    ansible.builtin.debug:
      msg: "course is  {{ courses | dict2items }}"


  - name: convert list to map
    vars:
      courses: 
        - {'key': 'name', 'value': 'devops'}
        - {'key': 'duration', 'value': '2 months'}
        - {'key': 'platform', 'value': 'joindevops'}
    ansible.builtin.debug:
      msg: "course info  {{ courses | items2dict }}"

  - name: convert Upper to lower
    vars:
      name: "DEVOPS"
    ansible.builtin.debug:
      msg: "course is  {{ name | lower }}"    

  - name: convert lower to upper    
    vars:
      name: "devops"
    ansible.builtin.debug:
      msg: "course is  {{ name | upper }}"

      