- name: shell vs command
  hosts: local
  connection: local
  tasks:
  - name: execute ls command
    # ansible.builtin.command: ls -ltr > /tmp/output.txt
    ansible.builtin.shell: ls -ltr > /tmp/output.txt

  - name: execute ls command
    ansible.builtin.command: ls -ltr 
    register: output

  - name: print output
    ansible.builtin.debug:
      msg: "{{ output.stdout_lines }}" 