- name: Creating ec2 instances and r53 records
  hosts: local
  connection: local
  vars:
    subnet_id: subnet-0e727fe5208897d2f
    sg_id: sg-0a1bd5b7b329fa9dc
    instance_type: t3.micro
    ami_id: ami-09c813fb71547fc4f
    instances:
     - mysql
     - backend
     - frontend
     
  tasks:
  - name: install AWS phython libraries
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
      - boto3
      - botocore
  - name: Creating ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item}}"
      subnet_id: "{{ subnet_id }}"
      security_group: "{{ sg_id }}"
      instance_type: "{{ instance_type }}"
      image_id: "{{ ami_id }}"
    loop: "{{ instances }}"
    register: ec2_info
