- name: Creating ec2 instances and r53 records
  hosts: local
  connection: local
  vars:
    subnet_id: subnet-0e727fe5208897d2f
    sg_id: sg-0a1bd5b7b329fa9dc
    instance_type: t3.micro
    ami_id: ami-09c813fb71547fc4f
    Zone: salearnings.tech
    instances:
     - mysql
     - backend
     - frontend
     
  tasks:
  - name: install AWS phython libraries
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
      - boto3
      - botocore

  - name: Creating ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item}}"
      subnet_id: "{{ subnet_id }}"
      security_group: "{{ sg_id }}"
      instance_type: "{{ instance_type }}"
      image_id: "{{ ami_id }}"
    loop: "{{ instances }}"
    register: ec2_info

  # - name: print ec2 info
  #   ansible.builtin.debug:
  #     msg: "{{ ec2_info }}"
  
  - name: print private ip
    ansible.builtin.debug:
      msg: "{{ item.instances[0].private_ip_address }}"
    loop: "{{ ec2_info.results }}"

  - name: create private ip r53 records
    amazon.aws.route53:
    state: present
    zone: "{{ Zone }}"
    record: "{{item.item}}.{{ zone }}"
    type: A
    ttl: 1
    value: "{{ item.instances[0].private_ip_address }}"
    wait: true
    overwrite: true
    loop: "{{ ec2_info.results }}"